services:
  - type: web
    name: cocoon-ml-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    pythonVersion: 3.10
